### PR TITLE
Added a console log. Removed everything else

### PR DESCRIPTION
**Pull request by stevendaoud**
Please approve my pull request for the sake of Asgard.

### CODE REVIEW

**Comment by CalicoHero** [comment]
bitmoji

**Review by MattMurn — APPROVED** [review]

**Comment by MattMurn** [comment]
Sorry I didn't leave a comment. I was trying to use Bitmoji but I don't use SnapChat

**Comment by MattMurn** [comment]
I heard they laid off they're entire development team...

**Comment by CalicoHero** [comment]
@MattMurn Bitmoji is also a separate app I think. Don't know if you can use it solo.

**Comment by MattMurn** [comment]
Aye. I'll check it out. EXTENSION REMOVED!!!!

**Pull request merged**
